name: Prevent file change in PR
description: Fail a pull request workflow if certain files are changed
author: Dharmalife
inputs:
  pattern:
    required: true
    description: JavaScript regular expression matching filenames (including path) of files which must not be changed
  trusted-authors:
    required: false
    description: 'Always trust pull request authors included in this comma separated list, e.g.: user1, user2, user3'
  token:
    required: true
    description: Token to access the repository
    default: ${{ github.token }}
runs:
  using: node16
  main: dist/index.js
